name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Compile Contracts
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v2

    - name: Use node@12
      uses: actions/setup-node@v1
      with: { node-version: '12.x' }

    - name: Install dependencies
      run: yarn --frozen-lockfile
      
    - name: Compile smart-contracts
      run: yarn compile

  build:
    name: Unit Tests
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v2

    - name: Use node@12
      uses: actions/setup-node@v1
      with: { node-version: '12.x' }

    - name: Install dependencies
      run: yarn --frozen-lockfile
      
    - name: Run tests
      run: yarn test